spring.datasource.url=jdbc:postgresql://dpg-d91gkugjs32c739cm3ag-a.oregon-postgres.render.com/jobtracker_sv6d
spring.datasource.username=nicolas
spring.datasource.password=KMibTKe2MkrxFpHuRu58uFmil7S8Nytb
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080