spring.datasource.url=jdbc:postgresql://nicolas:KMibTKe2MkrxFpHuRu58uFmil7S8Nytb@dpg-d91gkugjs32c739cm3ag-a.oregon-postgres.render.com/jobtracker_sv6d
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
server.port=${PORT:8080}