# URL de Conexão Direta (Garanta o jdbc:postgresql:// no começo)
spring.datasource.url=jdbc:postgresql://nicolas:KMibTKe2MkrxFpHuRu58uFmil7S8Nytb@dpg-d91gkugjs32c739cm3ag-a.oregon-postgres.render.com/jobtracker_sv6d

# Credenciais explícitas (ajuda o driver a não se perder na string longa)
spring.datasource.username=nicolas
spring.datasource.password=KMibTKe2MkrxFpHuRu58uFmil7S8Nytb
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do Hibernate para Spring Boot moderno
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Porta que a Render espera encontrar
server.port=${PORT:8080}